name: n8n

services:
  n8n:
    depends_on:
      n8n-postgres:
        condition: service_healthy
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: database
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      # DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: password
      WEBHOOK_URL: https://lenient-really-badger.ngrok-free.app
      NODE_FUNCTION_ALLOW_EXTERNAL: uuid,xlsx
    ports:
      - 5678:5678
    volumes:
      - n8n-data:/home/node/.n8n
    links:
      - n8n-postgres
  
  n8n-postgres:
    container_name: n8n-postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_NON_ROOT_USER: app
      POSTGRES_NON_ROOT_PASSWORD: app
    volumes:
      - n8n-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d database']
      interval: 5s
      timeout: 5s
      retries: 10
  
  n8n-ngrok:
    container_name: n8n-ngrok
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    env_file:
      - ./.env
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - n8n

volumes:
  n8n-pgdata:
  n8n-data: